### ISSUE TITLE
SimpleShaderProgramBuilder with DiscardTransparentFragments set throws ShaderCompilationException

### ISSUE THREAD

**Issue by TheRut** [ThomasMiz/TrippyGL#6]
Repro Steps:
1. Create a SimpleShaderProgramBuilder
2. Set DiscardTransparentFragments to true
3. Build shader

Expected Results: Shader generate correclty
Actual Results: TrippyGL.ShaderCompilationException: 'FragmentShaderArb didn't compile properly: 
0(16) : error C1048: invalid character 'A' in swizzle "A"
'

Cause is in SimpleShaderProgramBuilder.cs line 303, the GLSL code "if (finalColor.A <" is invalid, the A should be lowercase.

**Comment by ThomasMiz** [comment]
Damn this is a bit embarrassing 💀 I'm surprised I didn't catch this before

I've already pushed a commit fixing this and it seems to be working fine now. Thanks for reporting!

I'm considering releasing a new minor version with bugfixes such as this one soon, but first I want to see what happens with PR #5
