### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by perdub** [ThomasMiz/TrippyGL#8]
Hello, today, when i tryed to load `Texture2D` with `Texture2DExtensions`, i get a `System.MissingMethodException: Method not found`

Code to load: `texturea = Texture2DExtensions.FromImage(device, SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>("1.jpg"));`

Full stacktrace: 
```
Unhandled exception. System.MissingMethodException: Method not found: 'Boolean SixLabors.ImageSharp.Image`1.TryGetSinglePixelSpan(System.Span`1<!0> ByRef)'.
   at TrippyGL.ImageSharp.Texture2DExtensions.FromImage(GraphicsDevice graphicsDevice, Image`1 image, Boolean generateMipmaps)
   at silknetlearn.GameWindow.Load() in D:\C#\silknetlearn\Program.cs:line 84
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at silknetlearn.GameWindow..ctor() in D:\C#\silknetlearn\Program.cs:line 46
   at silknetlearn.Program.Main(String[] args) in D:\C#\silknetlearn\Program.cs:line 16
```

**Comment by ThomasMiz** [comment]
Hello! It seems you're using a newer version of ImageSharp than TrippyGL. TrippyGL 1.1.1 uses ImageSharp 1.0.4 and does not support ImageSharp 2.X and up. That said, the update to fix this is already in the update-imagesharp branch, but that branch is waiting for a new version of SixLabors.Fonts to finalize some things before it's merged.

If possible, I recommend not installing the ImageSharp package manually, but instead letting TrippyGL bring as dependency the version it needs. You can also simplify your code to just ```texturea = Texture2DExtensions.FromFile(device, "1.jpg");```

In the meantime, if you _need_ one of the newer versions of ImageSharp, you can build TrippyGL from source from the update-imagesharp branch, or you can [copy the new extension files from that branch into your project](https://github.com/SilkCommunity/TrippyGL/tree/update-imagesharp/TrippyGL.ImageSharp).

Hope that helps!

**Comment by ThomasMiz** [comment]
[TrippyGL 1.2.0 has been released to NuGet with this fix!](https://www.nuget.org/packages/TrippyGL.ImageSharp/1.2.0)
